global:
  scrape_interval: 15s

scrape_configs:
  - job_name: "gateway-service"
    scrape_interval: 30s
    metrics_path: "/actuator/prometheus"
    static_configs:
      - targets: ["gateway-service:8080"]